research_prospect_task:
  description: >
    Conduct thorough research on {name}, their role as
    {title} at {company}, and the company itself.
    Look for recent news, achievements, challenges, or interests related to
    {name} or their company in the {industry} industry.
    Use their LinkedIn profile ({linkedin_url}) and other publicly
    available sources to gather relevant information.
    Important: When using search or website scraping tools, provide only the search query string or the website URL respectively as the input, not a JSON object.
  expected_output: >
    A detailed dossier on {name} and {company},
    including recent professional activities, potential pain points, interests,
    and any other information that could be used to personalize communication.

personalize_content_task:
  description: >
    Using the research on {name} and {company},
    identify specific ways that {our_product} can address their potential needs
    or align with their professional interests. Look for unique angles or shared
    points of interest that can be used to create a strong personal connection
    in the email.
  expected_output: >
    A list of personalized talking points and angles to use in the email,
    connecting {name}'s background, interests, or challenges
    with the benefits of {our_product}.

write_email_task:
  description: >
    Craft a highly personalized email to {name} about {our_product}.
    1. Use the research and personalized content to create an email that feels individual, relevant, and engaging. 
    2. The email should demonstrate understanding of their role and challenges, showcase how {our_product} can provide value,
       and invite further conversation.
    3. Format your response as a structured object with the fields below. This will be automatically processed 
       and sent to our API endpoint for database storage.
    4. Make sure to create a concise but compelling subject line that will grab {name}'s attention.
  expected_output: >
    A PersonalizedEmail object containing:
    1. A compelling, personalized subject line (not more than 10 words)
    2. The body of the email, written in a conversational yet professional tone 
    3. Follow-up notes for the sales person, suggesting potential talking points for future interactions
    
    The system will automatically send this email data to our API endpoint with {name} and {email_address}.
